Mnaveau/solo 12
open-dynamic-robot-initiative/robot_properties_solo pull request #9
Opened 2019-11-26 13:58 UTC by MaximilienNaveau

## What changed?

Create a dgm_parameters_solo8 and a dgm_parameters_solo12.

## How did I tested it:

To be tested:
- in simulation
- in the real robot

2019-11-26 16:03 UTC, jviereck requested changes

2019-11-26 16:03 UTC, jviereck commented on config/dgm_parameters_solo8.yaml
> +# @file dgm_parameters_solo8.yaml
You have to update the `Solo8Config` and `Solo12Config` `yaml_path` as well.

https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/master/python/robot_properties_solo/config.py#L69
https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/master/python/robot_properties_solo/config.py#L129

2019-11-26 16:07 UTC, jviereck requested changes

2019-11-26 16:07 UTC, jviereck commented on config/dgm_parameters_solo12.yaml
> +      size: 2
For compatibility with `solo8`, please use `size: 4` for the sliders here.

2019-12-12 16:48 UTC, MaximilienNaveau commented
I fixed this python/config.py after a rebase and force push.

2019-12-16 02:43 UTC, jviereck approved these changes

2019-12-16 10:31 UTC, MaximilienNaveau commented
Thanks @jviereck for checking the PR, I would not merge it right away as it would break dg_blmc_robots. The PR is gonna come once I double checked that the DGM works on Solo12.

2020-01-09 13:24 UTC, merged